In [1]:
#installing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
# !pip install pandas
# !pip install matplotlib
# !pip install scikit-learn
# !pip install seaborn
# !pip install xgboost

In [3]:
#importing data
data = pd.read_csv('RTA Dataset.csv')
pd.set_option('display.max_columns', 40)
pd.set_option('display.max_rows', 40)

In [4]:
data.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,No defect,Residential areas,NaN,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside-parked vehicles,2,2,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,No defect,Office areas,Undivided Two way,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,No defect,Recreational areas,other,NaN,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside objects,2,2,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,No defect,Office areas,other,Tangent road with mild grade and flat terrain,Y Shape,Earth roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,No defect,Industrial areas,other,Tangent road with flat terrain,Y Shape,Asphalt roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

In [5]:
data.nunique()

In [6]:
data.dtypes

In [7]:
data.describe(include = 'object')

In [8]:
data.isnull().sum()

In [9]:
#creating a function to check for multiple things
def define(data_,column):
    
    print(f'{column} : {data_[column].unique()}')
    print(f'NULL VALUES : {data_[column].isnull().sum()}')
    print(f'UNIQUE VALUES : {data_[column].nunique()}')
    print(f'MOST FREQUENT VALUE : {data_[column].mode(0)}')
    print('---------------------------------------------------------')

In [1]:
data['Day_of_week'].nunique()

In [12]:
import seaborn as sns
plt.figure(figsize = (25,10))
sns.countplot(x = data['Educational_level'],data = data)

## Age of drivers whose Education is unknown

In [13]:
data1 = data[data['Educational_level'] == 'Unknown']
sns.countplot(x = data1['Age_band_of_driver'],data = data1)

In [14]:
sns.countplot(x = data['Sex_of_driver'], data = data)

In [15]:
plt.figure(figsize = (25,10))
sns.countplot(x = data['Cause_of_accident'], data = data)
plt.tick_params(axis='both', labelsize=20,rotation = 90)

In [16]:
g = sns.catplot(x="Sex_of_driver", hue="Driving_experience", col="Accident_severity",
                data=data, kind="count",
                height=4, aspect=.9)
g.set_xticklabels(rotation=30)

In [17]:
g = sns.catplot(x="Light_conditions", col="Accident_severity",
                data=data, kind="count",
                height=4, aspect=.9)
g.set_xticklabels(rotation=90)

In [18]:
data.head()

In [19]:
data.shape

# Preprocessing

In [20]:
data.isnull().sum()

In [21]:
for col in df.columns:    
        define(df,col)

In [22]:
df = data.copy(deep = True)

In [23]:
df.replace('na',np.nan,inplace = True)

In [24]:
df.isna().mean()*100

In [25]:
df['Service_year_of_vehicle'] = df['Service_year_of_vehicle'].fillna(df['Service_year_of_vehicle'].mode()[0])

df['Service_year_of_vehicle'].replace(np.nan,'Unknown',inplace = True)

df['Service_year_of_vehicle'].value_counts()

In [28]:
df.isna().sum()

In [29]:
for cols in df.columns:
    if df[cols].isna().mean()*100>10:
        define(df,cols)

Defect_of_vehicle : ['No defect' nan '7' '5']
NULL VALUES : 4427
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    No defect
dtype: object
---------------------------------------------------------
Casualty_class : [nan 'Driver or rider' 'Pedestrian' 'Passenger']
NULL VALUES : 4443
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    Driver or rider
dtype: object
---------------------------------------------------------
Sex_of_casualty : [nan 'Male' 'Female']
NULL VALUES : 4443
UNIQUE VALUES : 2
MOST FREQUENT VALUE : 0    Male
dtype: object
---------------------------------------------------------
Age_band_of_casualty : [nan '31-50' '18-30' 'Under 18' 'Over 51' '5']
NULL VALUES : 4443
UNIQUE VALUES : 5
MOST FREQUENT VALUE : 0    NaN
dtype: object
---------------------------------------------------------
Casualty_severity : [nan '3' '2' '1']
NULL VALUES : 4443
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    3
dtype: object
---------------------------------------------------------
Work_of_casuality : [nan 'Driver' 'Other' 'Unemployed' 'Employee' 'Self-employed' 'Student'
 'Unknown']
NULL VALUES : 3198
UNIQUE VALUES : 7
MOST FREQUENT VALUE : 0    Driver
dtype: object
---------------------------------------------------------
Fitness_of_casuality : [nan 'Normal' 'Deaf' 'Other' 'Blind' 'NormalNormal']
NULL VALUES : 2635
UNIQUE VALUES : 5
MOST FREQUENT VALUE : 0    Normal
dtype: object
---------------------------------------------------------

In [30]:
df['Fitness_of_casuality'].replace('NormalNormal','Normal',inplace = True)

In [31]:
Nan_cols = ['Defect_of_vehicle ','Casualty_class','Sex_of_casualty ','Age_band_of_casualty']

In [32]:
df.isna().sum()
data.shape

In [33]:
for cols in df.columns:
    if df[cols].isnull().sum()>1:
        df[cols] = df[cols].fillna(df[cols].mode()[0])

In [34]:
df.replace('other','Other',inplace = True)
df.replace('unknown','Unknown',inplace = True)
df.replace('Unknown','Other',inplace = True)

In [35]:
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,No defect,Residential areas,Two-way (divided with broken lines road marking),Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside-parked vehicles,2,2,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,No defect,Office areas,Undivided Two way,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,2,2,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,Other,No defect,Recreational areas,Other,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside objects,2,2,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,Other,No defect,Office areas,Other,Tangent road with mild grade and flat terrain,Y Shape,Earth roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Owner,5-10yrs,No defect,Industrial areas,Other,Tangent road with flat terrain,Y Shape,Asphalt roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Slight Injury

In [36]:
df = df[df['Area_accident_occured']!='Rural village areasOffice areas']

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [38]:
le_cols = ['Sex_of_driver','Age_band_of_driver',
           'Vehicle_driver_relation','Type_of_vehicle','Owner_of_vehicle','Service_year_of_vehicle',
           'Area_accident_occured','Lanes_or_Medians','Road_allignment','Types_of_Junction','Road_surface_type',
           'Road_surface_conditions','Light_conditions','Weather_conditions','Type_of_collision','Vehicle_movement',
           'Sex_of_casualty','Work_of_casuality','Fitness_of_casuality','Pedestrian_movement','Cause_of_accident','Day_of_week',
          'Accident_severity','Casualty_class','Educational_level','Driving_experience','Age_band_of_casualty']

In [41]:
df_cleaned = df.copy(deep = True)
my_path = 'D:/TMLC/project_1/labels/'
for columns in le_cols:

    df_cleaned[columns] = le.fit_transform(df_cleaned[columns])
    new_path = f'{my_path}{columns}.pkl'
    output = open(new_path, 'wb')
    pickle.dump(le, output)
    output.close()

In [43]:
pkl_file = open('D:/TMLC/project_1/labels/Accident_severity.pkl','rb')
le = pickle.load(pkl_file)
int(le.transform(['Fatal injury']))

0

In [54]:
test = [1,2,3,4,5]
[test]

[[1, 2, 3, 4, 5]]

In [41]:
df_cleaned.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,1,0,1,0,0,0,0,3,3,No defect,9,3,5,1,0,0,3,2,3,2,2,2,0,1,0,3,0,2,5,9,2
1,17:02:00,1,1,1,4,0,3,11,3,2,No defect,6,5,5,1,0,0,3,2,7,2,2,2,0,1,0,3,0,2,5,16,2
2,17:02:00,1,0,1,4,0,0,5,3,5,No defect,1,2,5,1,0,0,3,2,2,2,2,2,0,1,1,3,0,2,5,0,1
3,1:06:00,3,0,1,4,0,2,11,0,5,No defect,6,2,6,6,2,0,0,2,7,2,2,2,2,0,0,3,0,2,5,1,2
4,1:06:00,3,0,1,4,0,1,0,3,2,No defect,4,2,5,6,0,0,0,2,7,2,2,2,0,1,0,3,0,2,5,16,2

In [42]:
df_cleaned['Defect_of_vehicle'].replace('No defect', 0,inplace = True)

In [43]:
df_cleaned['Age_band_of_casualty'].value_counts()

0    7574
1    2450
4    1034
3     994
2     244
Name: Age_band_of_casualty, dtype: int64

In [44]:
df_cleaned.isnull().sum()

Time                           0
Day_of_week                    0
Age_band_of_driver             0
Sex_of_driver                  0
Educational_level              0
Vehicle_driver_relation        0
Driving_experience             0
Type_of_vehicle                0
Owner_of_vehicle               0
Service_year_of_vehicle        0
Defect_of_vehicle              0
Area_accident_occured          0
Lanes_or_Medians               0
Road_allignment                0
Types_of_Junction              0
Road_surface_type              0
Road_surface_conditions        0
Light_conditions               0
Weather_conditions             0
Type_of_collision              0
Number_of_vehicles_involved    0
Number_of_casualties           0
Vehicle_movement               0
Casualty_class                 0
Sex_of_casualty                0
Age_band_of_casualty           0
Casualty_severity              0
Work_of_casuality              0
Fitness_of_casuality           0
Pedestrian_movement            0
Cause_of_accident              0
Accident_severity              0
dtype: int64

In [45]:
df_cleaned['Time'] = pd.to_datetime(df_cleaned['Time'])

df_cleaned['hour'] = df_cleaned['Time'].dt.hour

df_cleaned['Sin_hour'] = np.sin(2 * np.pi * df_cleaned['hour'] / max(df_cleaned['hour']))
df_cleaned['Cos_hour'] = np.cos(2 * np.pi * df_cleaned['hour']/max(df_cleaned['hour']))

In [46]:
df_cleaned.head(10)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity,hour,Sin_hour,Cos_hour
0,2022-07-21 17:02:00,1,0,1,0,0,0,0,3,3,0,9,3,5,1,0,0,3,2,3,2,2,2,0,1,0,3,0,2,5,9,2,17,-0.997669,-0.068242
1,2022-07-21 17:02:00,1,1,1,4,0,3,11,3,2,0,6,5,5,1,0,0,3,2,7,2,2,2,0,1,0,3,0,2,5,16,2,17,-0.997669,-0.068242
2,2022-07-21 17:02:00,1,0,1,4,0,0,5,3,5,0,1,2,5,1,0,0,3,2,2,2,2,2,0,1,1,3,0,2,5,0,1,17,-0.997669,-0.068242
3,2022-07-21 01:06:00,3,0,1,4,0,2,11,0,5,0,6,2,6,6,2,0,0,2,7,2,2,2,2,0,0,3,0,2,5,1,2,1,0.269797,0.962917
4,2022-07-21 01:06:00,3,0,1,4,0,1,0,3,2,0,4,2,5,6,0,0,0,2,7,2,2,2,0,1,0,3,0,2,5,16,2,1,0.269797,0.962917
5,2022-07-21 14:15:00,0,1,1,4,1,2,0,3,5,0,7,3,5,6,0,0,3,2,7,1,1,10,0,1,1,3,0,2,5,14,2,14,-0.631088,-0.775711
6,2022-07-21 17:30:00,6,0,1,4,0,1,0,3,5,0,9,5,5,0,0,0,3,2,7,1,1,3,0,0,0,3,0,2,5,13,2,17,-0.997669,-0.068242
7,2022-07-21 17:20:00,0,0,1,4,0,1,0,0,3,0,9,2,5,6,0,0,3,2,7,2,1,10,0,1,0,3,0,2,5,12,2,17,-0.997669,-0.068242
8,2022-07-21 17:20:00,0,0,1,4,0,3,5,3,0,0,4,2,5,6,2,0,3,2,3,2,1,2,2,1,4,3,0,2,0,1,2,17,-0.997669,-0.068242
9,2022-07-21 17:20:00,0,0,1,4,0,0,0,3,1,0,9,5,5,6,0,0,3,2,3,2,1,10,1,1,0,3,0,2,5,9,1,17,-0.997669,-0.068242

In [47]:
df_cleaned.drop(columns = ['Time','hour'],axis = 1,inplace = True)

In [48]:
# plt.figure(figsize = (30,30))
# sns.heatmap(df_cleaned.corr(), cmap="YlGnBu", annot=True)

In [49]:
y = df_cleaned['Accident_severity']
x = df_cleaned.drop('Accident_severity',axis = 1)

In [50]:
for cols in x.columns:
    if x.dtypes[cols] == 'object':
        x[cols] = x[cols].astype(int)

In [51]:
x.head()

,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Sin_hour,Cos_hour
0,1,0,1,0,0,0,0,3,3,0,9,3,5,1,0,0,3,2,3,2,2,2,0,1,0,3,0,2,5,9,-0.997669,-0.068242
1,1,1,1,4,0,3,11,3,2,0,6,5,5,1,0,0,3,2,7,2,2,2,0,1,0,3,0,2,5,16,-0.997669,-0.068242
2,1,0,1,4,0,0,5,3,5,0,1,2,5,1,0,0,3,2,2,2,2,2,0,1,1,3,0,2,5,0,-0.997669,-0.068242
3,3,0,1,4,0,2,11,0,5,0,6,2,6,6,2,0,0,2,7,2,2,2,2,0,0,3,0,2,5,1,0.269797,0.962917
4,3,0,1,4,0,1,0,3,2,0,4,2,5,6,0,0,0,2,7,2,2,2,0,1,0,3,0,2,5,16,0.269797,0.962917

In [52]:
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,No defect,Residential areas,Two-way (divided with broken lines road marking),Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside-parked vehicles,2,2,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,No defect,Office areas,Undivided Two way,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,2,2,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,Other,No defect,Recreational areas,Other,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside objects,2,2,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,Other,No defect,Office areas,Other,Tangent road with mild grade and flat terrain,Y Shape,Earth roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,Automobile,Owner,5-10yrs,No defect,Industrial areas,Other,Tangent road with flat terrain,Y Shape,Asphalt roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Overtaking,Slight Injury

In [53]:
for cols in df.columns:
    define(df,cols)

Time : ['17:02:00' '1:06:00' '14:15:00' ... '7:24:00' '19:18:00' '2:47:00']
NULL VALUES : 0
UNIQUE VALUES : 1074
MOST FREQUENT VALUE : 0    15:30:00
dtype: object
---------------------------------------------------------
Day_of_week : ['Monday' 'Sunday' 'Friday' 'Wednesday' 'Saturday' 'Thursday' 'Tuesday']
NULL VALUES : 0
UNIQUE VALUES : 7
MOST FREQUENT VALUE : 0    Friday
dtype: object
---------------------------------------------------------
Age_band_of_driver : ['18-30' '31-50' 'Under 18' 'Over 51' 'Other']
NULL VALUES : 0
UNIQUE VALUES : 5
MOST FREQUENT VALUE : 0    18-30
dtype: object
---------------------------------------------------------
Sex_of_driver : ['Male' 'Female' 'Other']
NULL VALUES : 0
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    Male
dtype: object
---------------------------------------------------------
Educational_level : ['Above high school' 'Junior high school' 'Elementary school'
 'High school' 'Other' 'Illiterate' 'Writing & reading']
NULL VALUES : 0
UNIQUE VALUES : 7
MOST FREQUENT VALUE : 0    Junior high school
dtype: object
---------------------------------------------------------
Vehicle_driver_relation : ['Employee' 'Other' 'Owner']
NULL VALUES : 0
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    Employee
dtype: object
---------------------------------------------------------
Driving_experience : ['1-2yr' 'Above 10yr' '5-10yr' '2-5yr' 'No Licence' 'Below 1yr' 'Other']
NULL VALUES : 0
UNIQUE VALUES : 7
MOST FREQUENT VALUE : 0    5-10yr
dtype: object
---------------------------------------------------------
Type_of_vehicle : ['Automobile' 'Public (> 45 seats)' 'Lorry (41?100Q)'
 'Public (13?45 seats)' 'Lorry (11?40Q)' 'Long lorry' 'Public (12 seats)'
 'Taxi' 'Pick up upto 10Q' 'Stationwagen' 'Ridden horse' 'Other' 'Bajaj'
 'Turbo' 'Motorcycle' 'Special vehicle' 'Bicycle']
NULL VALUES : 0
UNIQUE VALUES : 17
MOST FREQUENT VALUE : 0    Automobile
dtype: object
---------------------------------------------------------
Owner_of_vehicle : ['Owner' 'Governmental' 'Organization' 'Other']
NULL VALUES : 0
UNIQUE VALUES : 4
MOST FREQUENT VALUE : 0    Owner
dtype: object
---------------------------------------------------------
Service_year_of_vehicle : ['Above 10yr' '5-10yrs' 'Other' '1-2yr' '2-5yrs' 'Below 1yr']
NULL VALUES : 0
UNIQUE VALUES : 6
MOST FREQUENT VALUE : 0    Other
dtype: object
---------------------------------------------------------
Defect_of_vehicle : ['No defect' '7' '5']
NULL VALUES : 0
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    No defect
dtype: object
---------------------------------------------------------
Area_accident_occured : ['Residential areas' 'Office areas' '  Recreational areas'
 ' Industrial areas' 'Other' ' Church areas' '  Market areas'
 'Rural village areas' ' Outside rural areas' ' Hospital areas'
 'School areas' 'Recreational areas']
NULL VALUES : 0
UNIQUE VALUES : 12
MOST FREQUENT VALUE : 0    Other
dtype: object
---------------------------------------------------------
Lanes_or_Medians : ['Two-way (divided with broken lines road marking)' 'Undivided Two way'
 'Other' 'Double carriageway (median)' 'One way'
 'Two-way (divided with solid lines road marking)']
NULL VALUES : 0
UNIQUE VALUES : 6
MOST FREQUENT VALUE : 0    Two-way (divided with broken lines road marking)
dtype: object
---------------------------------------------------------
Road_allignment : ['Tangent road with flat terrain'
 'Tangent road with mild grade and flat terrain' 'Escarpments'
 'Tangent road with rolling terrain' 'Gentle horizontal curve'
 'Tangent road with mountainous terrain and'
 'Steep grade downward with mountainous terrain' 'Sharp reverse curve'
 'Steep grade upward with mountainous terrain']
NULL VALUES : 0
UNIQUE VALUES : 9
MOST FREQUENT VALUE : 0    Tangent road with flat terrain
dtype: object
---------------------------------------------------------
Types_of_Junction : ['No junction' 'Y Shape' 'Crossing' 'O Shape' 'Other' 'T Shape' 'X Shape']
NULL VALUES : 0
UNIQUE VALUES : 7
MOST FREQUENT VALUE : 0    Y Shape
dtype: object
---------------------------------------------------------
Road_surface_type : ['Asphalt roads' 'Earth roads' 'Asphalt roads with some distress'
 'Gravel roads' 'Other']
NULL VALUES : 0
UNIQUE VALUES : 5
MOST FREQUENT VALUE : 0    Asphalt roads
dtype: object
---------------------------------------------------------
Road_surface_conditions : ['Dry' 'Wet or damp' 'Snow' 'Flood over 3cm. deep']
NULL VALUES : 0
UNIQUE VALUES : 4
MOST FREQUENT VALUE : 0    Dry
dtype: object
---------------------------------------------------------
Light_conditions : ['Daylight' 'Darkness - lights lit' 'Darkness - no lighting'
 'Darkness - lights unlit']
NULL VALUES : 0
UNIQUE VALUES : 4
MOST FREQUENT VALUE : 0    Daylight
dtype: object
---------------------------------------------------------
Weather_conditions : ['Normal' 'Raining' 'Raining and Windy' 'Cloudy' 'Other' 'Windy' 'Snow'
 'Fog or mist']
NULL VALUES : 0
UNIQUE VALUES : 8
MOST FREQUENT VALUE : 0    Normal
dtype: object
---------------------------------------------------------
Type_of_collision : ['Collision with roadside-parked vehicles'
 'Vehicle with vehicle collision' 'Collision with roadside objects'
 'Collision with animals' 'Other' 'Rollover' 'Fall from vehicles'
 'Collision with pedestrians' 'With Train']
NULL VALUES : 0
UNIQUE VALUES : 9
MOST FREQUENT VALUE : 0    Vehicle with vehicle collision
dtype: object
---------------------------------------------------------
Number_of_vehicles_involved : [2 1 3 6 4 7]
NULL VALUES : 0
UNIQUE VALUES : 6
MOST FREQUENT VALUE : 0    2
dtype: int64
---------------------------------------------------------
Number_of_casualties : [2 1 3 4 6 5 8 7]
NULL VALUES : 0
UNIQUE VALUES : 8
MOST FREQUENT VALUE : 0    1
dtype: int64
---------------------------------------------------------
Vehicle_movement : ['Going straight' 'U-Turn' 'Moving Backward' 'Turnover' 'Waiting to go'
 'Getting off' 'Reversing' 'Other' 'Parked' 'Stopping' 'Overtaking'
 'Entering a junction']
NULL VALUES : 0
UNIQUE VALUES : 12
MOST FREQUENT VALUE : 0    Going straight
dtype: object
---------------------------------------------------------
Casualty_class : ['Driver or rider' 'Pedestrian' 'Passenger']
NULL VALUES : 0
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    Driver or rider
dtype: object
---------------------------------------------------------
Sex_of_casualty : ['Male' 'Female']
NULL VALUES : 0
UNIQUE VALUES : 2
MOST FREQUENT VALUE : 0    Male
dtype: object
---------------------------------------------------------
Age_band_of_casualty : ['18-30' '31-50' 'Under 18' 'Over 51' '5']
NULL VALUES : 0
UNIQUE VALUES : 5
MOST FREQUENT VALUE : 0    18-30
dtype: object
---------------------------------------------------------
Casualty_severity : ['3' '2' '1']
NULL VALUES : 0
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    3
dtype: object
---------------------------------------------------------
Work_of_casuality : ['Driver' 'Other' 'Unemployed' 'Employee' 'Self-employed' 'Student']
NULL VALUES : 0
UNIQUE VALUES : 6
MOST FREQUENT VALUE : 0    Driver
dtype: object
---------------------------------------------------------
Fitness_of_casuality : ['Normal' 'Deaf' 'Other' 'Blind']
NULL VALUES : 0
UNIQUE VALUES : 4
MOST FREQUENT VALUE : 0    Normal
dtype: object
---------------------------------------------------------
Pedestrian_movement : ['Not a Pedestrian' "Crossing from driver's nearside"
 'Crossing from nearside - masked by parked or statioNot a Pedestrianry vehicle'
 'Unknown or other'
 'Crossing from offside - masked by  parked or statioNot a Pedestrianry vehicle'
 'In carriageway, statioNot a Pedestrianry - not crossing  (standing or playing)'
 'Walking along in carriageway, back to traffic'
 'Walking along in carriageway, facing traffic'
 'In carriageway, statioNot a Pedestrianry - not crossing  (standing or playing) - masked by parked or statioNot a Pedestrianry vehicle']
NULL VALUES : 0
UNIQUE VALUES : 9
MOST FREQUENT VALUE : 0    Not a Pedestrian
dtype: object
---------------------------------------------------------
Cause_of_accident : ['Moving Backward' 'Overtaking' 'Changing lane to the left'
 'Changing lane to the right' 'Overloading' 'Other'
 'No priority to vehicle' 'No priority to pedestrian' 'No distancing'
 'Getting off the vehicle improperly' 'Improper parking' 'Overspeed'
 'Driving carelessly' 'Driving at high speed' 'Driving to the left'
 'Overturning' 'Turnover' 'Driving under the influence of drugs'
 'Drunk driving']
NULL VALUES : 0
UNIQUE VALUES : 19
MOST FREQUENT VALUE : 0    No distancing
dtype: object
---------------------------------------------------------
Accident_severity : ['Slight Injury' 'Serious Injury' 'Fatal injury']
NULL VALUES : 0
UNIQUE VALUES : 3
MOST FREQUENT VALUE : 0    Slight Injury
dtype: object
---------------------------------------------------------

In [ ]:
x.head()xsads
x['Defect_of_vehicle'].value_counts()

In [ ]:
cols_to_scale = ['Type_of_vehicle','Defect_of_vehicle','Area_accident_occured','Road_allignment','Types_of_Junction',
                 'Weather_conditions','Type_of_collision',
                'Number_of_vehicles_involved','Vehicle_movement','Cause_of_accident']

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
x[cols_to_scale] = scaler.fit_transform(x[cols_to_scale])

In [ ]:
x.head()

# Upsampling the minority class

In [ ]:
# !pip install imblearn
from imblearn.over_sampling import SMOTE,BorderlineSMOTE
from collections import Counter

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [ ]:
counter = Counter(y_train)

In [ ]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

In [ ]:
counter = Counter(y_train)

print("=============================")

for k,v in counter.items():
    per = 100*v/len(y_train)
    print(f"Class= {k}, n={v} ({per:.2f}%)")

oversample = SMOTE()
x_train, y_train = oversample.fit_resample(x_train, y_train)

counter = Counter(y_train)

print("=============================")

for k,v in counter.items():
    per = 100*v/len(y_train)
    print(f"Class= {k}, n={v} ({per:.2f}%)")

print("=============================")

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
lr = LogisticRegression(max_iter = 3000)
rf = RandomForestClassifier(max_depth = None)
et = ExtraTreesClassifier()

In [ ]:
def performance(model,x_train,y_train,x_test,y_test):
    model.fit(x_train,y_train)
    model_pred = model.predict(x_test)
    f1 = f1_score(y_test,model_pred,average = 'weighted')
    print(f'{model} : {f1}')

In [ ]:
models = [lr,rf,et]
for model in models:
    performance(model,x_train,y_train,x_test,y_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
rf_pred = rf.predict(x_test)

In [ ]:
sns.heatmap(cm,annot = True,fmt = '',cmap = 'Greens')

# Hyperparameter Tuning

In [ ]:
param_grid = {
    'n_estimators' : [50,100,150,200],
    'max_depth' : [2,5,7,9,'None'],
    'min_samples_split' : [1,2,3,4,5],
    'ccp_alpha' : [0.0,0.1,0.2]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
gsearch = GridSearchCV(estimator = rf,param_grid = param_grid,cv = 5,n_jobs = -1,scoring = 'f1_weighted')

In [ ]:
gsearch.fit(x_train,y_train)

In [ ]:
(gsearch.best_params_, gsearch.best_score_)

In [ ]:
rf_tuned = RandomForestClassifier(ccp_alpha= 0.0,
  max_depth= 9,
  min_samples_split= 4,
  n_estimators= 200)

In [ ]:
rf_tuned.fit(x_train,y_train)

In [ ]:
rf_tuned_pred = rf_tuned.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test,rf_tuned_pred)

sns.heatmap(cm,annot = True,fmt = '')